import type {RemotionRenderInput} from "./types";

export const sampleInput: RemotionRenderInput = {
  video: {
    width: 1080,
    height: 1920,
    fps: 30,
    total_duration_seconds: 24,
    ticker: "ADBE",
    company: "Adobe",
    date: "2026-05-29",
    disclaimer: "Educational only. Not financial advice.",
    price: "$256.79",
    change_pct: "+6.4%",
    direction: "up",
  },
  template: {
    template_id: "three_things",
    template_name: "Three Things",
    scene_order: ["hook_card", "price_move_card", "chart_card", "takeaway_card"],
  },
  scenes: [
    {
      scene_index: 0,
      scene_type: "hook",
      card_type: "hook_card",
      start_seconds: 0,
      end_seconds: 6,
      duration_seconds: 6,
      narration: "Adobe jumped today after investors reacted to a new catalyst.",
      headline: "Adobe jumped 6% today",
      subheadline: "A sharp move needs context",
      detail_text: "Investors reacted to a new catalyst and repriced the enterprise software setup.",
      bullets: [],
      caption_text: "Adobe jumped 6% today",
      source_ids: [],
      sources: [],
      caption_beats: [],
      visual_beats: [],
      asset_public_paths: [],
    },
    {
      scene_index: 1,
      scene_type: "price_action",
      card_type: "price_move_card",
      start_seconds: 6,
      end_seconds: 12,
      duration_seconds: 6,
      narration: "The move stood out against recent trading.",
      headline: "Price action",
      subheadline: "The move stood out",
      detail_text: "The move stood out against recent trading and shifted short-term sentiment.",
      bullets: [],
      caption_text: "The move stood out",
      source_ids: [],
      sources: [],
      caption_beats: [],
      visual_beats: [],
      asset_public_paths: [],
    },
    {
      scene_index: 2,
      scene_type: "chart",
      card_type: "chart_card",
      start_seconds: 12,
      end_seconds: 18,
      duration_seconds: 6,
      narration: "The chart still gives useful price context.",
      headline: "Chart check",
      subheadline: "Price context",
      detail_text: "The latest snapshot shows a sharper move than the recent range.",
      bullets: [],
      caption_text: "Price context",
      source_ids: [],
      sources: [],
      caption_beats: [],
      visual_beats: [],
      chart: {
        title: "Price context",
        source: "latest market snapshot",
        synthetic: true,
        points: [
          {date: "2026-05-18", close: 241, volume: 1000, change_percent: 0},
          {date: "2026-05-19", close: 242, volume: 1100, change_percent: 0},
          {date: "2026-05-20", close: 243.5, volume: 1180, change_percent: 0},
          {date: "2026-05-21", close: 246, volume: 1210, change_percent: 0},
          {date: "2026-05-22", close: 250, volume: 1300, change_percent: 0},
          {date: "2026-05-29", close: 256.79, volume: 1600, change_percent: 6.4},
        ],
      },
      asset_public_paths: [],
    },
    {
      scene_index: 3,
      scene_type: "conclusion",
      card_type: "takeaway_card",
      start_seconds: 18,
      end_seconds: 24,
      duration_seconds: 6,
      narration: "Earnings decide whether the rally can last.",
      headline: "Earnings decide if this rally lasts",
      subheadline: "Separate the catalyst from valuation",
      detail_text: "The catalyst matters, but the next report decides whether the move can hold.",
      bullets: ["Watch the next report", "Compare price to fundamentals"],
      caption_text: "Earnings decide if this rally lasts",
      source_ids: [],
      sources: [],
      caption_beats: [],
      visual_beats: [],
      asset_public_paths: [],
    },
  ],
  assets: [],
};
